"""Hybrid graphics setup and power profile management."""

import os
import re
import shutil
import subprocess
from pathlib import Path

from nvidia_inst.utils.logger import get_logger

logger = get_logger(__name__)

HYBRID_ENV_FILE = "/etc/environment.d/90-nvidia-hybrid.conf"

HYBRID_ENV_CONTENT = """# NVIDIA PRIME Render Offload configuration
# Generated by nvidia-inst for hybrid graphics support
# This enables the integrated GPU for display and NVIDIA GPU for rendering on-demand

__NV_PRIME_RENDER_OFFLOAD=1
__GLX_VENDOR_LIBRARY_NAME=nvidia
"""


def get_hybrid_packages(distro_id: str) -> list[str]:
    """Get packages needed for hybrid graphics support.

    Args:
        distro_id: Distribution ID from detect_distro().

    Returns:
        List of package names to install, or empty list if not needed.
    """
    packages = {
        "fedora": ["switcheroo-control"],
        "rhel": ["switcheroo-control"],
        "centos": ["switcheroo-control"],
        "rocky": ["switcheroo-control"],
        "alma": ["switcheroo-control"],
        "opensuse": [],
        "sles": [],
        "ubuntu": [],
        "pop": [],
        "linuxmint": [],
        "debian": [],
        "arch": [],
        "manjaro": [],
        "cachyos": [],
        "endeavouros": [],
    }

    return packages.get(distro_id, [])


def install_hybrid_packages(packages: list[str], package_manager: str) -> bool:
    """Install packages for hybrid graphics support.

    Args:
        packages: List of package names to install.
        package_manager: Package manager name ('apt', 'dnf', 'pacman', 'zypper').

    Returns:
        True if installation succeeded, False otherwise.
    """
    if not packages:
        logger.debug("No hybrid packages needed for this distro")
        return True

    if package_manager == "apt":
        return _install_apt(packages)
    elif package_manager == "dnf":
        return _install_dnf(packages)
    elif package_manager == "pacman":
        return _install_pacman(packages)
    elif package_manager == "zypper":
        return _install_zypper(packages)

    logger.warning(f"Unknown package manager: {package_manager}")
    return False


def _install_apt(packages: list[str]) -> bool:
    """Install packages using apt."""
    try:
        subprocess.run(
            ["apt-get", "install", "-y"] + packages,
            capture_output=True,
            check=True,
        )
        return True
    except subprocess.CalledProcessError as e:
        logger.error(f"Failed to install hybrid packages: {e}")
        return False


def _install_dnf(packages: list[str]) -> bool:
    """Install packages using dnf."""
    try:
        subprocess.run(
            ["dnf", "install", "-y"] + packages,
            capture_output=True,
            check=True,
        )
        return True
    except subprocess.CalledProcessError as e:
        logger.error(f"Failed to install hybrid packages: {e}")
        return False


def _install_pacman(packages: list[str]) -> bool:
    """Install packages using pacman."""
    try:
        subprocess.run(
            ["pacman", "-Sy", "--noconfirm"] + packages,
            capture_output=True,
            check=True,
        )
        return True
    except subprocess.CalledProcessError as e:
        logger.error(f"Failed to install hybrid packages: {e}")
        return False


def _install_zypper(packages: list[str]) -> bool:
    """Install packages using zypper."""
    try:
        subprocess.run(
            ["zypper", "install", "-y"] + packages,
            capture_output=True,
            check=True,
        )
        return True
    except subprocess.CalledProcessError as e:
        logger.error(f"Failed to install hybrid packages: {e}")
        return False


def configure_prime_env() -> bool:
    """Configure PRIME Render Offload via environment file.

    Creates /etc/environment.d/90-nvidia-hybrid.conf which enables
    PRIME Render Offload system-wide.

    Returns:
        True if configuration succeeded, False otherwise.
    """
    if os.geteuid() != 0:
        logger.error("Root privileges required to configure hybrid graphics")
        return False

    try:
        env_dir = Path(HYBRID_ENV_FILE).parent
        env_dir.mkdir(parents=True, exist_ok=True)

        Path(HYBRID_ENV_FILE).write_text(HYBRID_ENV_CONTENT)
        logger.info(f"Created PRIME configuration at {HYBRID_ENV_FILE}")
        return True
    except OSError as e:
        logger.error(f"Failed to create PRIME configuration: {e}")
        return False


def get_power_profile(native_tool: str | None) -> str | None:
    """Get current power profile/mode.

    Args:
        native_tool: Name of native hybrid tool available.

    Returns:
        Current power mode string, or None if unable to determine.
    """
    if native_tool == "nvidia-prime":
        return _get_prime_select_mode()
    elif native_tool == "switcherooctl":
        return _get_switcherooctl_mode()
    elif native_tool == "system76-power":
        return _get_system76_mode()

    return None


def _get_prime_select_mode() -> str | None:
    """Get current mode from prime-select."""
    try:
        result = subprocess.run(
            ["prime-select", "query"],
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def _get_switcherooctl_mode() -> str | None:
    """Get current mode from switcherooctl."""
    try:
        result = subprocess.run(
            ["switcherooctl", "control", "-s"],
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def _get_system76_mode() -> str | None:
    """Get current mode from system76-power."""
    try:
        result = subprocess.run(
            ["system76-power", "graphics"],
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def set_power_profile(mode: str, native_tool: str | None, distro_id: str) -> bool:
    """Set power profile/mode for hybrid graphics.

    Args:
        mode: Power mode to set ('intel', 'hybrid', 'nvidia', etc.).
        native_tool: Name of native hybrid tool available.
        distro_id: Distribution ID.

    Returns:
        True if setting succeeded, False otherwise.
    """
    if native_tool == "nvidia-prime":
        return _set_prime_select_mode(mode)
    elif native_tool == "switcherooctl":
        return _set_switcherooctl_config(mode)
    elif native_tool == "system76-power":
        return _set_system76_mode(mode)

    if native_tool is None:
        logger.warning("No native hybrid tool available")
        return False

    return False


def _set_prime_select_mode(mode: str) -> bool:
    """Set mode using prime-select.

    Args:
        mode: Mode to set ('intel', 'on-demand', 'nvidia').

    Returns:
        True if succeeded, False otherwise.
    """
    if mode == "intel":
        target = "intel"
    elif mode == "nvidia":
        target = "nvidia"
    else:
        target = "on-demand"

    try:
        subprocess.run(
            ["pkexec", "prime-select", target],
            capture_output=True,
            check=True,
        )
        logger.info(f"Set power profile to {target}")
        return True
    except subprocess.CalledProcessError as e:
        logger.error(f"Failed to set power profile: {e}")
        return False


def _set_switcherooctl_config(mode: str) -> bool:
    """Set GPU mode by editing /etc/switcherooctl.conf.

    Args:
        mode: Mode to set ('intel', 'nvidia').

    Returns:
        True if succeeded, False otherwise.
    """
    if mode == "hybrid":
        logger.warning("switcherooctl does not support hybrid mode")
        return False

    if mode == "intel":
        gpu_mode = "integrated"
    elif mode == "nvidia":
        gpu_mode = "dedicated"
    else:
        return False

    if os.geteuid() != 0:
        logger.error("Root privileges required to modify switcherooctl config")
        return False

    config_path = Path("/etc/switcherooctl.conf")

    try:
        if config_path.exists():
            shutil.copy2(config_path, f"{config_path}.bak")
            content = config_path.read_text()
        else:
            content = ""

        if "session_gpu" in content:
            content = re.sub(
                r"session_gpu\s*=\s*\w+",
                f"session_gpu = {gpu_mode}",
                content,
            )
        else:
            if "[General]" in content:
                content = re.sub(
                    r"(\[General\])",
                    rf"\1\nsession_gpu = {gpu_mode}",
                    content,
                )
            else:
                content = f"[General]\nsession_gpu = {gpu_mode}\n"

        config_path.write_text(content)
        logger.info(f"Set switcherooctl session_gpu to {gpu_mode}")
        return True

    except OSError as e:
        logger.error(f"Failed to update switcherooctl config: {e}")
        return False


def _set_system76_mode(mode: str) -> bool:
    """Set mode using system76-power.

    Args:
        mode: Mode to set ('integrated', 'hybrid', 'nvidia', 'compute').

    Returns:
        True if succeeded, False otherwise.
    """
    if mode == "intel":
        target = "integrated"
    elif mode == "nvidia":
        target = "nvidia"
    else:
        target = mode

    try:
        subprocess.run(
            ["pkexec", "system76-power", "graphics", target],
            capture_output=True,
            check=True,
        )
        logger.info(f"Set power profile to {target}")
        return True
    except subprocess.CalledProcessError as e:
        logger.error(f"Failed to set power profile: {e}")
        return False


def is_prime_env_configured() -> bool:
    """Check if PRIME environment is already configured.

    Returns:
        True if environment file exists and is configured, False otherwise.
    """
    env_file = Path(HYBRID_ENV_FILE)
    if not env_file.exists():
        return False

    content = env_file.read_text()
    return "__NV_PRIME_RENDER_OFFLOAD=1" in content
